#!/bin/sh

# function to "declare" the database that exist
hasdb() {
	/usr/bin/mysql -s -u root $1 > /dev/null 2>&1 << EOF
EOF

	if [[ $? -eq 0 ]]; then
		return
	fi

	/usr/bin/mysql -uroot -s -e "create database $1; grant all privileges on $1.* to '$2'@'%' identified by '$3'; grant all privileges on $1.* to '$2'@'localhost' identified by '$3';" >/dev/null 2>&1
}

[ -e /etc/sysconfig/mysql ] && . /etc/sysconfig/mysql

